// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgzniwwzboqurchqbmbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnem5pd3d6Ym9xdXJjaHFibWJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MTcxMjYsImV4cCI6MjA2MDk5MzEyNn0.Db7SOeNLUUJ9fdMNz9YRQyh7-nEzC16Ez-9otOonqyA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);